### ISSUE TITLE
Create a good readme.md file

### ISSUE THREAD

**Issue by Shacklebolt13** [team-d3m0n1k/winbookBackend#5]

**Comment by mehraankush** [comment]
what would be the topic ..

**Comment by Shacklebolt13** [comment]
This is a small social media type Django backend with currently the basic login, posts, comments etc. make it about that, how to install this project, and where its currently hosted. which is: [here](https://winbookbackend.d3m0n1k.engineer)

**Comment by geek0ps** [comment]
@Shacklebolt13  Can i be assigned the task?
as i would be a great opportunity to be able to contribute to the project.

**Comment by Shacklebolt13** [comment]
Assigned ✔️

**Comment by geek0ps** [comment]
Thank you
